apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cz5qpzb07-go 
  janus-idp.io/tekton: cz5qpzb07-go
  backstage.io/kubernetes-id: cz5qpzb07-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz5qpzb07-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  