apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cz5qpzb07-go
  janus-idp.io/tekton: cz5qpzb07-go
  backstage.io/kubernetes-id: cz5qpzb07-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cz5qpzb07-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
